workflows:
  MindNet-workflow:
    name: MindNet Pipeline
    scripts:
      - name: CICD Started
        script: echo "CI/CD set up for MindNet"
      - name: Build MindNet
        script: - xcodebuild build -workspace "socialApp.xcworkspace" -scheme "socialApp" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients:
          - august9382@icloud.com

