workflows:
  MindNet-workflow:
    name: MindNet Pipeline
    scripts:
      - name: CICD Started
      script: echo "CI/CD set up for MindNet"
    publishing:
      email:
        recipients:
          - august9382@icloud.com

